module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  // Classes used only in server-generated task intro HTML (data_retriever.get_story_intro_html)
  safelist: [
    'task-intro',
    'task-message-html',
    'text-left',
    'text-lg',
    'font-bold',
    'text-indigo-800',
    'mb-3',
    'text-sm',
    'leading-relaxed',
    'text-gray-700',
    'font-semibold',
    'text-gray-800',
    'mb-2',
    'list-disc',
    'pl-5',
    'space-y-1',
    'mt-2',
    'p-3',
    'bg-amber-50',
    'rounded-lg',
    'border',
    'border-amber-200',
    'text-amber-900',
    'list-decimal',
    'text-amber-800',
    'font-medium',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
